#Should wand be able to shoot projectile.
shootProjectile = true
#How much FE to repair one use of wand. Zero to disable.
#Range: > 0
energyPerUse = 50
#Should use glowstone dust to repair wand.
repairRecipe = true
#Max durability of wand.
#Range: > 1
wandDurability = 255
#Range: > -2147483648
defaultLightColor = -683

